version: '3.8'

services:
  mysql:
    image: mysql:5.7.38
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=mmall
      - MYSQL_USER=mmall
      - MYSQL_PASSWORD=mmall