

spring:
  datasource:
    schema: "classpath:db/schema.sql"
    data: "classpath:db/data.sql"
    sql-script-encoding: UTF-8
    url: "jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=utf-8"
    username: "root"
    password: "root1234"
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  resources:
    chain:
      compressed: true
      cache: true
    cache:
      period: 86400

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
    com.github.kay: DEBUG

mmall:
  redis:
    url: redis://${redis.host:localhost}:${redis.tcp.6379:6379}
    host: ${redis.host:localhost}
    port: ${redis.tcp.6379:6379}
    connection-pool-size: 100
    connection-timeout: 15000
    lock-watchdog-timeout: 10000
    timeout: 5000
    retry-attempts: 50
    retry-interval: 5000
