version: '3.8'

services:
  mysql:
    image: mysql:5.7.38
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=mmall
      - MYSQL_USER=mmall
      - MYSQL_PASSWORD=mmall
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - network
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --notify-keyspace-events Ex
    networks:
      - network

networks:
  network:
    driver: bridge
    name: dev_network